export interface CountryCodeOption {
  iso: string;
  name: string;
  dialCode: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCodeOption[] = [
  { iso: 'NG', name: "Nigeria", dialCode: '+234', flag: 'NG' },
  { iso: 'AF', name: "Afghanistan", dialCode: '+93', flag: 'AF' },
  { iso: 'AL', name: "Albania", dialCode: '+355', flag: 'AL' },
  { iso: 'DZ', name: "Algeria", dialCode: '+213', flag: 'DZ' },
  { iso: 'AS', name: "American Samoa", dialCode: '+1-684', flag: 'AS' },
  { iso: 'AD', name: "Andorra", dialCode: '+376', flag: 'AD' },
  { iso: 'AO', name: "Angola", dialCode: '+244', flag: 'AO' },
  { iso: 'AI', name: "Anguilla", dialCode: '+1-264', flag: 'AI' },
  { iso: 'AQ', name: "Antarctica", dialCode: '+672', flag: 'AQ' },
  { iso: 'AG', name: "Antigua and Barbuda", dialCode: '+1-268', flag: 'AG' },
  { iso: 'AR', name: "Argentina", dialCode: '+54', flag: 'AR' },
  { iso: 'AM', name: "Armenia", dialCode: '+374', flag: 'AM' },
  { iso: 'AW', name: "Aruba", dialCode: '+297', flag: 'AW' },
  { iso: 'AU', name: "Australia", dialCode: '+61', flag: 'AU' },
  { iso: 'AT', name: "Austria", dialCode: '+43', flag: 'AT' },
  { iso: 'AZ', name: "Azerbaijan", dialCode: '+994', flag: 'AZ' },
  { iso: 'BS', name: "Bahamas", dialCode: '+1-242', flag: 'BS' },
  { iso: 'BH', name: "Bahrain", dialCode: '+973', flag: 'BH' },
  { iso: 'BD', name: "Bangladesh", dialCode: '+880', flag: 'BD' },
  { iso: 'BB', name: "Barbados", dialCode: '+1-246', flag: 'BB' },
  { iso: 'BY', name: "Belarus", dialCode: '+375', flag: 'BY' },
  { iso: 'BE', name: "Belgium", dialCode: '+32', flag: 'BE' },
  { iso: 'BZ', name: "Belize", dialCode: '+501', flag: 'BZ' },
  { iso: 'BJ', name: "Benin", dialCode: '+229', flag: 'BJ' },
  { iso: 'BM', name: "Bermuda", dialCode: '+1-441', flag: 'BM' },
  { iso: 'BT', name: "Bhutan", dialCode: '+975', flag: 'BT' },
  { iso: 'BO', name: "Bolivia", dialCode: '+591', flag: 'BO' },
  { iso: 'BA', name: "Bosnia and Herzegovina", dialCode: '+387', flag: 'BA' },
  { iso: 'BW', name: "Botswana", dialCode: '+267', flag: 'BW' },
  { iso: 'BR', name: "Brazil", dialCode: '+55', flag: 'BR' },
  { iso: 'IO', name: "British Indian Ocean Territory", dialCode: '+246', flag: 'IO' },
  { iso: 'VG', name: "British Virgin Islands", dialCode: '+1-284', flag: 'VG' },
  { iso: 'BN', name: "Brunei", dialCode: '+673', flag: 'BN' },
  { iso: 'BG', name: "Bulgaria", dialCode: '+359', flag: 'BG' },
  { iso: 'BF', name: "Burkina Faso", dialCode: '+226', flag: 'BF' },
  { iso: 'BI', name: "Burundi", dialCode: '+257', flag: 'BI' },
  { iso: 'KH', name: "Cambodia", dialCode: '+855', flag: 'KH' },
  { iso: 'CM', name: "Cameroon", dialCode: '+237', flag: 'CM' },
  { iso: 'CA', name: "Canada", dialCode: '+1', flag: 'CA' },
  { iso: 'CV', name: "Cape Verde", dialCode: '+238', flag: 'CV' },
  { iso: 'KY', name: "Cayman Islands", dialCode: '+1-345', flag: 'KY' },
  { iso: 'CF', name: "Central African Republic", dialCode: '+236', flag: 'CF' },
  { iso: 'TD', name: "Chad", dialCode: '+235', flag: 'TD' },
  { iso: 'CL', name: "Chile", dialCode: '+56', flag: 'CL' },
  { iso: 'CN', name: "China", dialCode: '+86', flag: 'CN' },
  { iso: 'CX', name: "Christmas Island", dialCode: '+61', flag: 'CX' },
  { iso: 'CC', name: "Cocos Islands", dialCode: '+61', flag: 'CC' },
  { iso: 'CO', name: "Colombia", dialCode: '+57', flag: 'CO' },
  { iso: 'KM', name: "Comoros", dialCode: '+269', flag: 'KM' },
  { iso: 'CK', name: "Cook Islands", dialCode: '+682', flag: 'CK' },
  { iso: 'CR', name: "Costa Rica", dialCode: '+506', flag: 'CR' },
  { iso: 'HR', name: "Croatia", dialCode: '+385', flag: 'HR' },
  { iso: 'CU', name: "Cuba", dialCode: '+53', flag: 'CU' },
  { iso: 'CW', name: "Curacao", dialCode: '+599', flag: 'CW' },
  { iso: 'CY', name: "Cyprus", dialCode: '+357', flag: 'CY' },
  { iso: 'CZ', name: "Czech Republic", dialCode: '+420', flag: 'CZ' },
  { iso: 'CD', name: "Democratic Republic of the Congo", dialCode: '+243', flag: 'CD' },
  { iso: 'DK', name: "Denmark", dialCode: '+45', flag: 'DK' },
  { iso: 'DJ', name: "Djibouti", dialCode: '+253', flag: 'DJ' },
  { iso: 'DM', name: "Dominica", dialCode: '+1-767', flag: 'DM' },
  { iso: 'DO', name: "Dominican Republic", dialCode: '+1-809', flag: 'DO' },
  { iso: 'DO', name: "Dominican Republic", dialCode: '+1-829', flag: 'DO' },
  { iso: 'DO', name: "Dominican Republic", dialCode: '+1-849', flag: 'DO' },
  { iso: 'TL', name: "East Timor", dialCode: '+670', flag: 'TL' },
  { iso: 'EC', name: "Ecuador", dialCode: '+593', flag: 'EC' },
  { iso: 'EG', name: "Egypt", dialCode: '+20', flag: 'EG' },
  { iso: 'SV', name: "El Salvador", dialCode: '+503', flag: 'SV' },
  { iso: 'GQ', name: "Equatorial Guinea", dialCode: '+240', flag: 'GQ' },
  { iso: 'ER', name: "Eritrea", dialCode: '+291', flag: 'ER' },
  { iso: 'EE', name: "Estonia", dialCode: '+372', flag: 'EE' },
  { iso: 'ET', name: "Ethiopia", dialCode: '+251', flag: 'ET' },
  { iso: 'FK', name: "Falkland Islands", dialCode: '+500', flag: 'FK' },
  { iso: 'FO', name: "Faroe Islands", dialCode: '+298', flag: 'FO' },
  { iso: 'FJ', name: "Fiji", dialCode: '+679', flag: 'FJ' },
  { iso: 'FI', name: "Finland", dialCode: '+358', flag: 'FI' },
  { iso: 'FR', name: "France", dialCode: '+33', flag: 'FR' },
  { iso: 'PF', name: "French Polynesia", dialCode: '+689', flag: 'PF' },
  { iso: 'GA', name: "Gabon", dialCode: '+241', flag: 'GA' },
  { iso: 'GM', name: "Gambia", dialCode: '+220', flag: 'GM' },
  { iso: 'GE', name: "Georgia", dialCode: '+995', flag: 'GE' },
  { iso: 'DE', name: "Germany", dialCode: '+49', flag: 'DE' },
  { iso: 'GH', name: "Ghana", dialCode: '+233', flag: 'GH' },
  { iso: 'GI', name: "Gibraltar", dialCode: '+350', flag: 'GI' },
  { iso: 'GR', name: "Greece", dialCode: '+30', flag: 'GR' },
  { iso: 'GL', name: "Greenland", dialCode: '+299', flag: 'GL' },
  { iso: 'GD', name: "Grenada", dialCode: '+1-473', flag: 'GD' },
  { iso: 'GU', name: "Guam", dialCode: '+1-671', flag: 'GU' },
  { iso: 'GT', name: "Guatemala", dialCode: '+502', flag: 'GT' },
  { iso: 'GG', name: "Guernsey", dialCode: '+44-1481', flag: 'GG' },
  { iso: 'GN', name: "Guinea", dialCode: '+224', flag: 'GN' },
  { iso: 'GW', name: "Guinea-Bissau", dialCode: '+245', flag: 'GW' },
  { iso: 'GY', name: "Guyana", dialCode: '+592', flag: 'GY' },
  { iso: 'HT', name: "Haiti", dialCode: '+509', flag: 'HT' },
  { iso: 'HN', name: "Honduras", dialCode: '+504', flag: 'HN' },
  { iso: 'HK', name: "Hong Kong", dialCode: '+852', flag: 'HK' },
  { iso: 'HU', name: "Hungary", dialCode: '+36', flag: 'HU' },
  { iso: 'IS', name: "Iceland", dialCode: '+354', flag: 'IS' },
  { iso: 'IN', name: "India", dialCode: '+91', flag: 'IN' },
  { iso: 'ID', name: "Indonesia", dialCode: '+62', flag: 'ID' },
  { iso: 'IR', name: "Iran", dialCode: '+98', flag: 'IR' },
  { iso: 'IQ', name: "Iraq", dialCode: '+964', flag: 'IQ' },
  { iso: 'IE', name: "Ireland", dialCode: '+353', flag: 'IE' },
  { iso: 'IM', name: "Isle of Man", dialCode: '+44-1624', flag: 'IM' },
  { iso: 'IL', name: "Israel", dialCode: '+972', flag: 'IL' },
  { iso: 'IT', name: "Italy", dialCode: '+39', flag: 'IT' },
  { iso: 'CI', name: "Ivory Coast", dialCode: '+225', flag: 'CI' },
  { iso: 'JM', name: "Jamaica", dialCode: '+1-876', flag: 'JM' },
  { iso: 'JP', name: "Japan", dialCode: '+81', flag: 'JP' },
  { iso: 'JE', name: "Jersey", dialCode: '+44-1534', flag: 'JE' },
  { iso: 'JO', name: "Jordan", dialCode: '+962', flag: 'JO' },
  { iso: 'KZ', name: "Kazakhstan", dialCode: '+7', flag: 'KZ' },
  { iso: 'KE', name: "Kenya", dialCode: '+254', flag: 'KE' },
  { iso: 'KI', name: "Kiribati", dialCode: '+686', flag: 'KI' },
  { iso: 'XK', name: "Kosovo", dialCode: '+383', flag: 'XK' },
  { iso: 'KW', name: "Kuwait", dialCode: '+965', flag: 'KW' },
  { iso: 'KG', name: "Kyrgyzstan", dialCode: '+996', flag: 'KG' },
  { iso: 'LA', name: "Laos", dialCode: '+856', flag: 'LA' },
  { iso: 'LV', name: "Latvia", dialCode: '+371', flag: 'LV' },
  { iso: 'LB', name: "Lebanon", dialCode: '+961', flag: 'LB' },
  { iso: 'LS', name: "Lesotho", dialCode: '+266', flag: 'LS' },
  { iso: 'LR', name: "Liberia", dialCode: '+231', flag: 'LR' },
  { iso: 'LY', name: "Libya", dialCode: '+218', flag: 'LY' },
  { iso: 'LI', name: "Liechtenstein", dialCode: '+423', flag: 'LI' },
  { iso: 'LT', name: "Lithuania", dialCode: '+370', flag: 'LT' },
  { iso: 'LU', name: "Luxembourg", dialCode: '+352', flag: 'LU' },
  { iso: 'MO', name: "Macau", dialCode: '+853', flag: 'MO' },
  { iso: 'MK', name: "Macedonia", dialCode: '+389', flag: 'MK' },
  { iso: 'MG', name: "Madagascar", dialCode: '+261', flag: 'MG' },
  { iso: 'MW', name: "Malawi", dialCode: '+265', flag: 'MW' },
  { iso: 'MY', name: "Malaysia", dialCode: '+60', flag: 'MY' },
  { iso: 'MV', name: "Maldives", dialCode: '+960', flag: 'MV' },
  { iso: 'ML', name: "Mali", dialCode: '+223', flag: 'ML' },
  { iso: 'MT', name: "Malta", dialCode: '+356', flag: 'MT' },
  { iso: 'MH', name: "Marshall Islands", dialCode: '+692', flag: 'MH' },
  { iso: 'MR', name: "Mauritania", dialCode: '+222', flag: 'MR' },
  { iso: 'MU', name: "Mauritius", dialCode: '+230', flag: 'MU' },
  { iso: 'YT', name: "Mayotte", dialCode: '+262', flag: 'YT' },
  { iso: 'MX', name: "Mexico", dialCode: '+52', flag: 'MX' },
  { iso: 'FM', name: "Micronesia", dialCode: '+691', flag: 'FM' },
  { iso: 'MD', name: "Moldova", dialCode: '+373', flag: 'MD' },
  { iso: 'MC', name: "Monaco", dialCode: '+377', flag: 'MC' },
  { iso: 'MN', name: "Mongolia", dialCode: '+976', flag: 'MN' },
  { iso: 'ME', name: "Montenegro", dialCode: '+382', flag: 'ME' },
  { iso: 'MS', name: "Montserrat", dialCode: '+1-664', flag: 'MS' },
  { iso: 'MA', name: "Morocco", dialCode: '+212', flag: 'MA' },
  { iso: 'MZ', name: "Mozambique", dialCode: '+258', flag: 'MZ' },
  { iso: 'MM', name: "Myanmar", dialCode: '+95', flag: 'MM' },
  { iso: 'NA', name: "Namibia", dialCode: '+264', flag: 'NA' },
  { iso: 'NR', name: "Nauru", dialCode: '+674', flag: 'NR' },
  { iso: 'NP', name: "Nepal", dialCode: '+977', flag: 'NP' },
  { iso: 'NL', name: "Netherlands", dialCode: '+31', flag: 'NL' },
  { iso: 'AN', name: "Netherlands Antilles", dialCode: '+599', flag: 'AN' },
  { iso: 'NC', name: "New Caledonia", dialCode: '+687', flag: 'NC' },
  { iso: 'NZ', name: "New Zealand", dialCode: '+64', flag: 'NZ' },
  { iso: 'NI', name: "Nicaragua", dialCode: '+505', flag: 'NI' },
  { iso: 'NE', name: "Niger", dialCode: '+227', flag: 'NE' },
  { iso: 'NU', name: "Niue", dialCode: '+683', flag: 'NU' },
  { iso: 'KP', name: "North Korea", dialCode: '+850', flag: 'KP' },
  { iso: 'MP', name: "Northern Mariana Islands", dialCode: '+1-670', flag: 'MP' },
  { iso: 'NO', name: "Norway", dialCode: '+47', flag: 'NO' },
  { iso: 'OM', name: "Oman", dialCode: '+968', flag: 'OM' },
  { iso: 'PK', name: "Pakistan", dialCode: '+92', flag: 'PK' },
  { iso: 'PW', name: "Palau", dialCode: '+680', flag: 'PW' },
  { iso: 'PS', name: "Palestine", dialCode: '+970', flag: 'PS' },
  { iso: 'PA', name: "Panama", dialCode: '+507', flag: 'PA' },
  { iso: 'PG', name: "Papua New Guinea", dialCode: '+675', flag: 'PG' },
  { iso: 'PY', name: "Paraguay", dialCode: '+595', flag: 'PY' },
  { iso: 'PE', name: "Peru", dialCode: '+51', flag: 'PE' },
  { iso: 'PH', name: "Philippines", dialCode: '+63', flag: 'PH' },
  { iso: 'PN', name: "Pitcairn", dialCode: '+64', flag: 'PN' },
  { iso: 'PL', name: "Poland", dialCode: '+48', flag: 'PL' },
  { iso: 'PT', name: "Portugal", dialCode: '+351', flag: 'PT' },
  { iso: 'PR', name: "Puerto Rico", dialCode: '+1-787', flag: 'PR' },
  { iso: 'PR', name: "Puerto Rico", dialCode: '+1-939', flag: 'PR' },
  { iso: 'QA', name: "Qatar", dialCode: '+974', flag: 'QA' },
  { iso: 'CG', name: "Republic of the Congo", dialCode: '+242', flag: 'CG' },
  { iso: 'RE', name: "Reunion", dialCode: '+262', flag: 'RE' },
  { iso: 'RO', name: "Romania", dialCode: '+40', flag: 'RO' },
  { iso: 'RU', name: "Russia", dialCode: '+7', flag: 'RU' },
  { iso: 'RW', name: "Rwanda", dialCode: '+250', flag: 'RW' },
  { iso: 'BL', name: "Saint Barthelemy", dialCode: '+590', flag: 'BL' },
  { iso: 'SH', name: "Saint Helena", dialCode: '+290', flag: 'SH' },
  { iso: 'KN', name: "Saint Kitts and Nevis", dialCode: '+1-869', flag: 'KN' },
  { iso: 'LC', name: "Saint Lucia", dialCode: '+1-758', flag: 'LC' },
  { iso: 'MF', name: "Saint Martin", dialCode: '+590', flag: 'MF' },
  { iso: 'PM', name: "Saint Pierre and Miquelon", dialCode: '+508', flag: 'PM' },
  { iso: 'VC', name: "Saint Vincent and the Grenadines", dialCode: '+1-784', flag: 'VC' },
  { iso: 'WS', name: "Samoa", dialCode: '+685', flag: 'WS' },
  { iso: 'SM', name: "San Marino", dialCode: '+378', flag: 'SM' },
  { iso: 'ST', name: "Sao Tome and Principe", dialCode: '+239', flag: 'ST' },
  { iso: 'SA', name: "Saudi Arabia", dialCode: '+966', flag: 'SA' },
  { iso: 'SN', name: "Senegal", dialCode: '+221', flag: 'SN' },
  { iso: 'RS', name: "Serbia", dialCode: '+381', flag: 'RS' },
  { iso: 'SC', name: "Seychelles", dialCode: '+248', flag: 'SC' },
  { iso: 'SL', name: "Sierra Leone", dialCode: '+232', flag: 'SL' },
  { iso: 'SG', name: "Singapore", dialCode: '+65', flag: 'SG' },
  { iso: 'SX', name: "Sint Maarten", dialCode: '+1-721', flag: 'SX' },
  { iso: 'SK', name: "Slovakia", dialCode: '+421', flag: 'SK' },
  { iso: 'SI', name: "Slovenia", dialCode: '+386', flag: 'SI' },
  { iso: 'SB', name: "Solomon Islands", dialCode: '+677', flag: 'SB' },
  { iso: 'SO', name: "Somalia", dialCode: '+252', flag: 'SO' },
  { iso: 'ZA', name: "South Africa", dialCode: '+27', flag: 'ZA' },
  { iso: 'KR', name: "South Korea", dialCode: '+82', flag: 'KR' },
  { iso: 'SS', name: "South Sudan", dialCode: '+211', flag: 'SS' },
  { iso: 'ES', name: "Spain", dialCode: '+34', flag: 'ES' },
  { iso: 'LK', name: "Sri Lanka", dialCode: '+94', flag: 'LK' },
  { iso: 'SD', name: "Sudan", dialCode: '+249', flag: 'SD' },
  { iso: 'SR', name: "Suriname", dialCode: '+597', flag: 'SR' },
  { iso: 'SJ', name: "Svalbard and Jan Mayen", dialCode: '+47', flag: 'SJ' },
  { iso: 'SZ', name: "Swaziland", dialCode: '+268', flag: 'SZ' },
  { iso: 'SE', name: "Sweden", dialCode: '+46', flag: 'SE' },
  { iso: 'CH', name: "Switzerland", dialCode: '+41', flag: 'CH' },
  { iso: 'SY', name: "Syria", dialCode: '+963', flag: 'SY' },
  { iso: 'TW', name: "Taiwan", dialCode: '+886', flag: 'TW' },
  { iso: 'TJ', name: "Tajikistan", dialCode: '+992', flag: 'TJ' },
  { iso: 'TZ', name: "Tanzania", dialCode: '+255', flag: 'TZ' },
  { iso: 'TH', name: "Thailand", dialCode: '+66', flag: 'TH' },
  { iso: 'TG', name: "Togo", dialCode: '+228', flag: 'TG' },
  { iso: 'TK', name: "Tokelau", dialCode: '+690', flag: 'TK' },
  { iso: 'TO', name: "Tonga", dialCode: '+676', flag: 'TO' },
  { iso: 'TT', name: "Trinidad and Tobago", dialCode: '+1-868', flag: 'TT' },
  { iso: 'TN', name: "Tunisia", dialCode: '+216', flag: 'TN' },
  { iso: 'TR', name: "Turkey", dialCode: '+90', flag: 'TR' },
  { iso: 'TM', name: "Turkmenistan", dialCode: '+993', flag: 'TM' },
  { iso: 'TC', name: "Turks and Caicos Islands", dialCode: '+1-649', flag: 'TC' },
  { iso: 'TV', name: "Tuvalu", dialCode: '+688', flag: 'TV' },
  { iso: 'VI', name: "U.S. Virgin Islands", dialCode: '+1-340', flag: 'VI' },
  { iso: 'UG', name: "Uganda", dialCode: '+256', flag: 'UG' },
  { iso: 'UA', name: "Ukraine", dialCode: '+380', flag: 'UA' },
  { iso: 'AE', name: "United Arab Emirates", dialCode: '+971', flag: 'AE' },
  { iso: 'GB', name: "United Kingdom", dialCode: '+44', flag: 'GB' },
  { iso: 'US', name: "United States", dialCode: '+1', flag: 'US' },
  { iso: 'UY', name: "Uruguay", dialCode: '+598', flag: 'UY' },
  { iso: 'UZ', name: "Uzbekistan", dialCode: '+998', flag: 'UZ' },
  { iso: 'VU', name: "Vanuatu", dialCode: '+678', flag: 'VU' },
  { iso: 'VA', name: "Vatican", dialCode: '+379', flag: 'VA' },
  { iso: 'VE', name: "Venezuela", dialCode: '+58', flag: 'VE' },
  { iso: 'VN', name: "Vietnam", dialCode: '+84', flag: 'VN' },
  { iso: 'WF', name: "Wallis and Futuna", dialCode: '+681', flag: 'WF' },
  { iso: 'EH', name: "Western Sahara", dialCode: '+212', flag: 'EH' },
  { iso: 'YE', name: "Yemen", dialCode: '+967', flag: 'YE' },
  { iso: 'ZM', name: "Zambia", dialCode: '+260', flag: 'ZM' },
  { iso: 'ZW', name: "Zimbabwe", dialCode: '+263', flag: 'ZW' },
];

export const defaultCountryCode = COUNTRY_CODES[0];

export function countryFlagEmoji(iso: string): string {
  const code = iso.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return code;
  return String.fromCodePoint(...Array.from(code).map((char) => 127397 + char.charCodeAt(0)));
}

export function formatPhoneWithCountryCode(dialCode: string, phone: string): string {
  const cleanCode = dialCode.trim();
  const cleanPhone = phone.trim().replace(/^[+0\s-]+/, '').replace(/\s+/g, '');
  if (!cleanPhone) return cleanCode;
  return `${cleanCode} ${cleanPhone}`;
}
